### ISSUE TITLE
Open source Terra

### ISSUE THREAD

**Issue by bensku** [starandserpent/Terra#11]
It has always been planned to open source Terra when time is right. So, let's call that time "milestone 0.0.2". Other things for that milestone will come later.

I and @deltasquad451 (assuming he works on Terra before this) will need to make sure that codebase is somewhat readable, does not contain anything that we don't want to share and so on. We all (that includes @Pilvinen) will probably want to have another talk about license, even though MIT gathered support when we last talked about this topic.

**Comment by Pilvinen** [comment]
Open sourced, so let's close this.
