### ISSUE TITLE
Fix broken unit tests

### ISSUE THREAD

**Issue by bensku** [starandserpent/Terra#13]
Some unit tests are broken at the moment, and they should be fixed. It is not a goal to write massive amount of new unit tests right now, though.

**Comment by Pilvinen** [comment]
If the tests are broken it might make sense to consider transition from the old JUnit 4 to the new JUnit 5 tests.

All the current tests are written in JUnit 4, so it would require some amount of effort.

**Comment by deltasquad451** [comment]
Fixed as of the following commit on the SplatTest: e030a0c3af8972d93d388cd78c0f67bf3143afc1 .

**Comment by Pawlost** [comment]
Fixed in splatter branch
