### ISSUE TITLE
Terra doesn't build with Java 10/11

### ISSUE THREAD

**Issue by Pilvinen** [starandserpent/Terra#31]
Terra doesn't build with Java 10/11.

You have to use Java 1.8 to get Gradle to build and then switch to Java 10/11.

Happens with IntelliJ IDEA.

NOTE: Needs more details.

**Comment by deltasquad451** [comment]
Issue seems to be resolved on DEV branch on the following setup:
- Windows 7
- OpenJDK 11
- Intellij IDEA
