### ISSUE TITLE
Terra does not load empty space

### ISSUE THREAD

**Issue by Pawlost** [starandserpent/Terra#37]
id is saved in MemoryArea as 0 in Palette16CriticalBuffer, but when it is converted to Storage in Palette16BlockBuffer then read value is 1
when the whole chunk is empty it works  right
1 is Dirt
0 is Air
this means that terra currently cannot create air

read and write methods in critical buffer work good
but read method in BufferWithFormat have the ID problem
it loads(reads) 0 as 1

**Comment by deltasquad451** [comment]
It seems as if the issue is related to the final block in the chunk

**Comment by Pawlost** [comment]
I fixed the issue related to the final block. Now we need to figure out ID problem.

**Comment by Pawlost** [comment]
We solved bug by increasing all ids by 1
