### ISSUE TITLE
Texture mapping is not working properly

### ISSUE THREAD

**Issue by Pilvinen** [starandserpent/Terra#42]
![https://i.snag.gy/D9f3Gs.jpg](https://i.snag.gy/D9f3Gs.jpg)

This is a really close closeup on the texture on one block. The pixels are visibly stretched.

![https://i.snag.gy/jhfNB1.jpg](https://i.snag.gy/jhfNB1.jpg)

This is a really close closeup from further away, again, on one block.  You can see the texture repeating. It should not repeat on this level. If I'd had estimate, I would say that the texture is repeating on one 25x25x25 cm block hundreds or even thousands of times.

This the cause behind the strange looking textures we've been having. The problem would have been obvious by using test textures, like I suggested.

![https://i.snag.gy/XvpaY7.jpg](https://i.snag.gy/XvpaY7.jpg)

Here's what the image actually should look like up close.

![https://i.snag.gy/W1NirT.jpg](https://i.snag.gy/W1NirT.jpg)

Here I replaced the textures with test textures and zoomed in really close. You get the idea.

**Comment by Pawlost** [comment]
I fixed textures calculation
