### ISSUE TITLE
Something is holding down chunk generation rate

### ISSUE THREAD

**Issue by Pilvinen** [starandserpent/Terra#55]
Naive greedy meshing now takes 8 ms on the average, but I'm not actually _seeing_ by eye the 1000 / 8 = 125 chunks per second generation rate which I should be seeing when I'm using only the naive greedy mesher.

There is a bottle neck somewhere down the line.

It needs to be tracked down and squashed.

**Comment by Pilvinen** [comment]
1941 chunks: 4 minutes 43 seconds. Measured from program start.
146 milliseconds per chunk of which meshing took ~9 ms per chunk on the average.
Triangle count in the scene was 9.87590 million triangles.

We're currently losing 137 ms somewhere.

Current sentiment is that it might be gobbled up by Palette16 compression / chunk creation, ie. chunk generation can't feed the mesher fast enough. Needs to be verified, though.

**Comment by Pawlost** [comment]
We found that filling chunks is holding generation

**Comment by Pawlost** [comment]
Since we are using Larray for chunk filling, the bottleneck is now minimal
