### ISSUE TITLE
Allow negative coordinates in Terra

### ISSUE THREAD

**Issue by Pawlost** [starandserpent/Terra#8]
This issue is related to https://github.com/starandserpent/Voxel-demo/issues/85.
This will require removing all bitwise operations in Terra, but it is only option if you want to alllow terrain generation in every direction. This is very important for Torus mapping which should happen even in negative coordinates.

**Comment by Pilvinen** [comment]
It is possible to represent negative numbers in binary using two's complement. There is no reason to start stripping optimizations for that reason.

**Comment by Pawlost** [comment]
![Capture](https://user-images.githubusercontent.com/32877330/94180174-e0058480-fe9d-11ea-9d51-1342e16fc1ec.PNG)

**Comment by Pawlost** [comment]
Can you elaborate more? I never heard of it.

**Comment by Pilvinen** [comment]
Sure. Here's an article on it:
https://janmr.com/blog/2010/07/bitwise-operators-and-negative-numbers/#:~:text=When%20representing%20integers%20using%20a,n%3D2n%E2%88%92x.

And you can Google "two's complement binary" to find more.
